FROM python:3-alpine
MAINTAINER John Sanabria <john.sanabria@correounivalle.edu.co>

RUN mkdir /shared
WORKDIR /shared

COPY requirements.txt /shared
RUN pip install --no-cache-dir -r requirements.txt

RUN rm requirements.txt
EXPOSE 5000

ENTRYPOINT ["python"]
