FROM postgres
MAINTAINER John Sanabria <john.sanabria@correounivalle.edu.co>

ENV req "requirements_psql.txt"

RUN apt-get -y update && apt-get install -y build-essential libpq-dev python2.7 python2.7-dev postgresql-contrib python-pip && pip install --upgrade pip

RUN mkdir /shared
WORKDIR /shared

COPY ${req} /shared
RUN pip install --upgrade --no-cache-dir -r ${req}

RUN rm ${req} && rm -r /root/.cache
ENTRYPOINT ["python"]
